export const POPULAR_MOVIES = 'POPULAR_MOVIE';
export const UPCOMING_MOVIES = 'UPCOMING_MOVIE';
export const FAVORITES_MOVIES = 'FAVORITES_MOVIES';
export const DETAIL_MOVIES = 'DETAIL_MOVIES';
export const FETCH_SEARCH_MOVIES = 'FETCH_SEARCH_MOVIES';
export const SHOW_RESULT_SEARCH = 'SHOW_RESULT_SEARCH';
export const FILTER_TABLE = 'FILTER_TABLE';
